-- 12.13  Calculating Subtotals for All Possible Expression Combinations
/*You want to find the sum of all salaries by DEPTNO, and by JOB, for every JOB/
DEPTNO combination. You also want a grand total for all salaries in table EMP. You
want to return the following result set

ANALYST TOTAL BY DEPT AND JOB 6000
CLERK TOTAL BY JOB 4150
ANALYST TOTAL BY JOB 6000
MANAGER TOTAL BY JOB 8275
PRESIDENT TOTAL BY JOB 5000
SALESMAN TOTAL BY JOB 5600
10 TOTAL BY DEPT 8750
30 TOTAL BY DEPT 9400
20 TOTAL BY DEPT 10875
GRAND TOTAL FOR TABLE 29025*/
use practice;

select * from emp_table;

select deptno,job,'TOTAL BY DEPT AND JOB' as category,
sum(sal) as sal
from emp_table
group by 1,2
union all
select deptno ,null, 'TOTAL BY DEPT' as category,sum(sal) as sal
from emp_table
group by 1
union all 
select null,job,'TOTAL BY JOB' as category,sum(sal) as sal
from emp_table
group by 2
union all
select null,null,'GRAND TOTAL FOR TABLE', sum(sal)
from emp_table;

-- 12.14 Identifying Rows That Are Not Subtotals (not supported in MySQL)
/*You’ve used the CUBE extension of the GROUP BY clause to create a report, and you
need a way to differentiate between rows that would be generated by a normal
GROUP BY clause and those rows that have been generated as a result of using CUBE
or ROLLUP.*/
-- CUBE FUNCTION 

/*how the CUBE/ROLLUP clauses are written:
1 select deptno, job, sum(sal) sal,
2 grouping(deptno) deptno_subtotals,
3 grouping(job) job_subtotals
4 from emp
5 group by deptno,job with cube*/
/*If DEPTNO_SUBTOTALS is 0 and JOB_SUBTOTALS is 1 (in which case JOB is
NULL), the value of SAL represents a subtotal of salaries by DEPTNO created by
CUBE. If JOB_SUBTOTALS is 0 and DEPTNO_SUBTOTALS is 1 (in which case
DEPTNO is NULL), the value of SAL represents a subtotal of salaries by JOB created
by CUBE. Rows with 0 for both DEPTNO_SUBTOTALS and JOB_SUBTOTALS rep‐
resent rows created by regular aggregation (the sum of SAL for each DEPTNO/JOB
combination).*/

-- 12.15  Using Case Expressions to Flag Rows

